---
title: "Untitled"
author: "Kalyani Cauwenberghs"
date: "1/31/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#function that will return the 5 things she asked for in a list, given a p
#usage example: we want p_hat for p=0.1
  #p0.1<-binom500(0.1)
  #p0.1$p_hat

binom500<-function(p){
  #simulate 500 bin(100,p)
  sims<-rbinom (500, 100, p)
  p_hats<-sims/100
  
  #avg. of estimated p’s
  avg_p_hats<-mean(p_hats)
  
  #empirical variance of the p_hat’s
  emp_var<-var(p_hats)
  
  #1 var estimator for each p_hat
  var_est<-p_hats*(1-p_hats)/100
  #avg. estimated variances of the p_hat’s
  avg_var<-mean(var_est)

  #proportion of 95% CI’s that contain true value of p
  CI<-matrix(0,500,2)
  CI[,1]<-t(t(p_hats-qnorm(.975)*sqrt(var_est)))
  CI[,2]<-t(t(p_hats+qnorm(.975)*sqrt(var_est)))
  true_CI_prop<-mean(p>=CI[,1]&p<=CI[,2])
  
  #avg. length of the 95% CI’s
  avg_CI_length<-mean(CI[,2]-CI[,1])
  
  return(c(avg_p_hats,emp_var,
              avg_var,true_CI_prop,
              avg_CI_length))
}
final<-data.frame(
           binom500(0.1),
           binom500(0.2),
           binom500(0.3),
           binom500(0.4),
           binom500(0.5), 
           row.names = 
             c("avg p_hats",
               "emp variance",
               "avg variance",
               "prop CI's contain p",
               "avg CI length")
           )
colnames(final)<-c("p=0.1","p=0.2","p=0.3","p=0.4","p=0.5")
knitr::kable(final)
```

