---
title: "week 5"
author: "Kalyani Cauwenberghs"
date: "2/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Research question:
Hypothesis: Let p = political freedom score/(pfs+efs). 
H_0: p in asia is the same as p in europe
H_1: p in asia is diff from p in europe
```{r}
data<-read.csv("hfi_cc_2019.csv")
data<-data[data$year=="2017",]
asia_oceania<-data[data$region=="South Asia"|
                     data$region=="Caucasus & Central Asia"|
                     data$region=="Oceania"|
                     data$region=="East Asia",]
europe<-data[data$region=="Eastern Europe"|
             data$region=="Western Europe",]
e_pf<-as.numeric(europe$pf_score)
e_ef<-as.numeric(europe$ef_score)
e<-((e_pf)/(e_pf+e_ef))
a_pf<-as.numeric(asia_oceania$pf_score)
a_ef<-as.numeric(asia_oceania$ef_score)
a<-((a_pf)/(a_pf+a_ef))
p_europe<-mean(e)
p_asia<-mean(a)
benchmark<-mean(c(e,a))
proportions<-data.frame("asia"=c(sum(a>benchmark),sum(a<benchmark)),
                        "europe"=c(sum(e>benchmark),sum(e<benchmark)),
                        row.names = c("above_mean", "below_mean"))
```
Let p = proportion of countries with greater than mean (across all of europe and asia) pf/(ef+pf).
```{r}
pe<-proportions[1,2]/sum(proportions$europe)
pa<-proportions[1,1]/sum(proportions$asia)
#confidence interval
est<-pe-pa
SE<-sqrt((pa*(1-pa)/sum(proportions$asia))+(pe*(1-pe)/sum(proportions$europe)))
CI<-c(est-qnorm(0.975)*SE,est+qnorm(0.975)*SE)
z<-est/SE
#percentile
pnorm(z)
#odds ratio
OR<-(pe*(1-pa))/(pa*(1-pe))
#chisq test
chisq.test(proportions)
#fischer
fisher.test(proportions)
```